#pragma once

#include "FileSystem/MediaInterface.h"

#include "Input/JoystickInterface.h"
#include "Input/KeyboardInterface.h"
#include "Input/MouseInterface.h"

#include "Renderer/Object3dInfoInterface.h"
#include "Renderer/ComputeStageInterface.h"
#include "Renderer/DescriptorSetInterface.h"
#include "Renderer/DescriptorSetLayoutInterface.h"
#include "Renderer/GenericBufferInterface.h"
#include "Renderer/ImageInterface.h"
#include "Renderer/RenderStageInterface.h"
#include "Renderer/ShaderModuleInterface.h"
#include "Renderer/ToolkitInterface.h"
#include "Renderer/SwapChainOutputInterface.h"
#include "Renderer/AttachmentInterface.h"
#include "Renderer/SemaphoreInterface.h"

#include "Renderer/Object3dInfoFactoryInterface.h"
#include "Renderer/ShaderFactoryInterface.h"
#include "Renderer/DescriptorSetLayoutFactoryInterface.h"
#include "Renderer/RenderStageFactoryInterface.h"
#include "Renderer/ComputeStageFactoryInterface.h"
#include "Renderer/BufferFactoryInterface.h"
#include "Renderer/ImageFactoryInterface.h"
#include "Renderer/SwapChainOutputFactoryInterface.h"
#include "Renderer/SemaphoreFactoryInterface.h"
